language: php
php:
  - 5.5
  - 5.4
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php:
          - hhvm
          - 5.6

install: composer install
script: phpunit --configuration teste/full.xml