language: php
php:
  - 5.5
  - 5.4
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php:
          - hhvm
          - 5.6

before_script: phpenv config-add travs-config.ini
install: composer install
script: phpunit --configuration teste/full.xml