language: php
php:
  - 5.5
  - 5.4
  - 5.6

matrix:
    allow_failures:
        - php:
          - 5.6

before_script: phpenv config-add travs-config.ini
install: composer install
script: phpunit --configuration tests/full.xml